import type { Metadata } from "next";
import { EB_Garamond } from "next/font/google";
import "./globals.css";

const garb = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${garb.className} antialiased text-gray-900 bg-[#e9d9bf]/50 min-h-screen flex flex-col`}
      >
        < main className="flex-1 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
